### PR TITLE
set up front-end prototype, finish data-binding, very ugly

### PR DESCRIPTION
**Pull request by shuowu**
@jichao06  Prototype, without related topics for story. You can run it by double click index.html. No style right now.

### CODE REVIEW

**Comment by shuowu** [comment]
refer to issue#6

**Comment by shuowu** [comment]
refer to Orion#6

**Comment by shuowu** [comment]
refer to https://github.com/shuowu/Orion/issues/6

**Comment by shuowu** [comment]
@jichao06  prototype finished, ready for review

**Comment by jichao06** [comment]
It was working although ugly. But after the last change. It stopped working. 

1. When I use Safari, I can see the list of topics on the index page, but click on one of them does not show stories. If I use chrome, I don't even see the topics on index page.

2. Suggestion. What we are showing on the index page is list of topics. So we could change the link on the top from 'News' to 'Topics'. After we click a topic a list of news would be shown. I remember seeing a title as topics there. We could change that to 'News'. Also, on the 'News' page, we could also show the list of topic keywords.

**Pull request merged**
